apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: set-prefect-scripts
  name: set-prefect-scripts
spec:
  selector:
    matchLabels:
      app: set-prefect-scripts
  template:
    metadata:
      labels:
        io.kompose.network/mc-default: "true"
        app: set-prefect-scripts
    spec:
      restartPolicy: Never
      containers:
        - name: set-prefect-scripts
          image: ghcr.io/aces-eu/workflowmanagement/set-prefect-scripts:v0.9
